import { Link, createFileRoute } from '@tanstack/react-router'
import { ArrowLeft, ArrowRight, CheckCircle2 } from 'lucide-react'

export const Route = createFileRoute('/a-propos')({
  head: () => ({ meta: [{ title: 'À propos | Cifra Conseils' }, { name: 'description', content: 'Découvrez l’approche de Cifra Conseils Inc. pour les PME québécoises.' }] }),
  component: About,
})

function About() {
  return <main className="min-h-dvh bg-background text-foreground"><header className="bg-[#0D1F2D] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6 lg:px-8"><Link to="/" className="flex items-center gap-2 text-sm text-white/70 hover:text-[#02C39A]"><ArrowLeft className="h-4 w-4" /> Retour à l’accueil</Link><img src="/cifra-conseil-logo.png" alt="Cifra Conseils" className="h-14 w-auto object-contain" /><Link to="/contact" className="text-sm text-[#02C39A]">Nous parler <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div></header><section className="mx-auto max-w-4xl px-5 py-20 lg:py-32"><p className="label-kicker">À propos</p><h1 className="mt-6 max-w-3xl font-serif text-5xl leading-tight sm:text-7xl">Une expertise solide. Une relation simple.</h1><p className="mt-8 max-w-2xl text-xl leading-8 text-muted-foreground">Cifra Conseils est né d’une conviction : les PME méritent le même niveau de rigueur financière que les grandes entreprises, sans perdre leur agilité ni leur proximité.</p><div className="mt-20 grid gap-12 border-t border-border pt-12 lg:grid-cols-[1fr_0.8fr]"><div><h2 className="font-serif text-3xl">Une expertise adaptée à votre réalité</h2><p className="mt-6 leading-8 text-muted-foreground">Notre approche combine rigueur financière, compréhension des opérations et recommandations concrètes. Chaque mandat commence par une écoute attentive de votre situation, de vos priorités et de vos objectifs.</p><p className="mt-5 leading-8 text-muted-foreground">Vous bénéficiez d’un accompagnement structuré, flexible et accessible, pensé pour les PME de Lévis, de Québec, de la Rive-Sud et des régions environnantes.</p></div><div className="rounded-[12px] bg-[#E2F5F0] p-8"><h3 className="font-semibold">Notre façon de travailler</h3><ul className="mt-6 space-y-4 text-sm leading-6">{['Écouter avant de recommander', 'Rendre les chiffres compréhensibles', 'Dire les choses avec franchise et respect', 'Construire une relation qui dure'].map(item => <li key={item} className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-[#028090]" />{item}</li>)}</ul></div></div><div className="mt-20 rounded-[12px] bg-[#0D1F2D] p-8 text-white sm:p-12"><h2 className="max-w-xl font-serif text-3xl sm:text-4xl">Vous n’avez pas besoin d’un titre de plus. Vous avez besoin de visibilité.</h2><Link to="/contact" className="mt-8 inline-flex rounded-[8px] bg-[#02C39A] px-5 py-3 font-semibold text-[#0D1F2D]">Discutons de vos besoins <ArrowRight className="ml-2 h-4 w-4" /></Link></div></section></main>
}
