import { useState } from 'react'
import { Link, createFileRoute } from '@tanstack/react-router'
import { ArrowLeft, ArrowRight, Check, Mail, MapPin, Phone } from 'lucide-react'
import { toast } from 'sonner'

export const Route = createFileRoute('/contact')({
  head: () => ({ meta: [{ title: 'Contact | Cifra Conseils' }, { name: 'description', content: 'Réservez une première conversation avec Cifra Conseils.' }] }),
  component: Contact,
})

function Contact() {
  const [sent, setSent] = useState(false)
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); toast.success('Votre demande a été envoyée.') }
  return <main suppressHydrationWarning className="min-h-dvh bg-[#0D1F2D] text-white"><header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6 lg:px-8"><Link to="/" className="flex items-center gap-2 text-sm text-white/70 hover:text-[#02C39A]"><ArrowLeft className="h-4 w-4" /> Accueil</Link><img src="/cifra-conseil-logo.png" alt="Cifra Conseils" className="h-14 w-auto object-contain" /><span className="w-16" /></header><section className="mx-auto grid max-w-7xl gap-14 px-5 py-16 lg:grid-cols-[0.8fr_1.2fr] lg:px-8 lg:py-28"><div><p className="label-kicker text-[#02C39A]">Premier échange</p><h1 className="mt-6 font-serif text-5xl leading-tight sm:text-7xl">Faisons le point.</h1><p className="mt-7 max-w-md text-lg leading-8 text-white/65">Parlez-nous de votre entreprise et de ce qui vous préoccupe. La première conversation est simple, directe et sans obligation.</p><div className="mt-12 space-y-6 text-white/75"><p className="flex gap-4"><Mail className="h-5 w-5 text-[#C8923A]" /> info@cifraconseils.ca</p><p className="flex gap-4"><Phone className="h-5 w-5 text-[#C8923A]" /> 418 555-0192</p><p className="flex gap-4"><MapPin className="h-5 w-5 text-[#C8923A]" /> Lévis, Québec</p></div></div><div className="rounded-[12px] bg-white p-6 text-[#0D1F2D] sm:p-10">{sent ? <div className="py-20 text-center"><Check className="mx-auto h-12 w-12 text-[#028090]" /><h2 className="mt-5 font-serif text-3xl">Merci pour votre confiance.</h2><p className="mt-4 text-muted-foreground">Votre message est bien arrivé. Nous vous contacterons bientôt.</p><Link to="/" className="mt-8 inline-flex items-center text-sm font-semibold text-[#028090]">Retour à l’accueil <ArrowRight className="ml-2 h-4 w-4" /></Link></div> : <form onSubmit={submit}><h2 className="font-serif text-3xl">Parlons de votre situation</h2><div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="field-label dark-field">Nom<input required placeholder="Votre nom" /></label><label className="field-label dark-field">Entreprise<input required placeholder="Votre entreprise" /></label><label className="field-label dark-field">Courriel<input required type="email" placeholder="vous@entreprise.ca" /></label><label className="field-label dark-field">Téléphone<input placeholder="418 555-0000" /></label></div><label className="field-label dark-field mt-5 block">Message<textarea required rows={6} placeholder="Comment pouvons-nous vous aider?"></textarea></label><button type="submit" className="mt-7 w-full rounded-[8px] bg-[#028090] px-5 py-4 font-semibold text-white transition-transform hover:scale-[1.02] active:scale-95">Envoyer ma demande <ArrowRight className="ml-2 inline h-4 w-4" /></button></form>}</div></section></main>
}
